Don't always use nix-shell; it slows down benchmarks

diff --git a/annotateAsts b/annotateAsts
--- a/annotateAsts
+++ b/annotateAsts
@@ -1,7 +1,11 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -p jq -i bash
+#!/usr/bin/env bash
 
 set -e
+
+command -v jq > /dev/null || {
+    echo "ERROR: annotateAsts requires jq" >> /dev/stderr
+    exit 1
+}
 
 BASE=$(dirname "$0")
 
diff --git a/getArities b/getArities
--- a/getArities
+++ b/getArities
@@ -1,5 +1,9 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -i bash -p jq
+#!/usr/bin/env bash
+
+command -v jq > /dev/null || {
+    echo "ERROR: getArities requires jq" >> /dev/stderr
+    exit 1
+}
 
 # Split a qualified name into a module and a name
 INPUT='(.qname | split(".") | reverse) as $bits'
diff --git a/getDeps b/getDeps
--- a/getDeps
+++ b/getDeps
@@ -1,5 +1,12 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -p getDeps -p bash -p jq -i bash
+#!/usr/bin/env bash
+
+for CMD in jq GetDeps
+do
+    command -v "$CMD" > /dev/null || {
+        echo "ERROR: getDeps needs '$CMD'" >> /dev/stderr
+        exit 1
+    }
+done
 
 jq -c '.[]' | while read -r LINE
 do
diff --git a/getTypes b/getTypes
--- a/getTypes
+++ b/getTypes
@@ -1,5 +1,9 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -i bash -p jq
+#!/usr/bin/env bash
+
+command -v jq > /dev/null || {
+    echo "ERROR: getTypes needs jq" >> /dev/stderr
+    exit 1
+}
 
 # Monomorphic types come in via stdin
 
