Don't use nix-shell automatically

diff --git a/dump-hackage b/dump-hackage
--- a/dump-hackage
+++ b/dump-hackage
@@ -1,7 +1,36 @@
 #!/usr/bin/env bash
 set -e
 
-DIR=$(mktemp -d)
+function findPkgInDir {
+    # Look through the contents of $DIR for entries of the form $1-1.2.3
+    for D in "$DIR"/*
+    do
+        if basename "$D" | grep "^$1-[0-9\.]*\$" > /dev/null
+        then
+            basename "$D"
+            return 0
+        fi
+    done
+    return 1
+}
+
+if [[ -n "$XDG_CACHE_HOME" ]] && [[ -d "$XDG_CACHE_HOME" ]]
+then
+    # On many systems, 'mktemp -d' will use an in-memory filesystem, which will
+    # quickly fill up. To avoid that, we try to use XDG_CACHE_HOME instead.
+    DIR=$(mkdir -p "$XDG_CACHE_HOME/cabal2db")
+elif [[ -n "$HOME" ]] && [[ -d "$HOME" ]]
+then
+    # If $HOME exists, try falling back to the recommended ~/.cache directory
+    DIR=$(mkdir -p "$HOME/.cache/cabal2db")
+else
+    # If $HOME doesn't exist, we're probably a daemon. Use mktemp, in the hope
+    # that it's sane.
+    DIR=$(mktemp -d "cabal2db")
+fi
+
+echo "Storing packages in '$DIR'" >> /dev/stderr
+
 BASE=$(dirname "$0")
 
 [[ -e "$BASE/dump-package" ]] || {
@@ -9,19 +38,23 @@ BASE=$(dirname "$0")
     exit 1
 }
 
-(cd "$DIR";
- for PKG in "$@"
- do
-     nix-shell --show-trace \
-               -p haskellPackages.cabal-install \
-               --run "cabal update; cabal get $PKG" >> /dev/stderr
- done)
+pushd "$DIR" > /dev/null
+for PKG in "$@"
+do
+    if PKGDIR=$(findPkgInDir "$PKG")
+    then
+        true
+    else
+        nix-shell --show-trace \
+                  -p haskellPackages.cabal-install \
+                  --run "cabal update; cabal get $PKG" >> /dev/stderr
+        PKGDIR=$(findPkgInDir "$PKG") || {
+            echo "Failed to get '$PKG', aborting" >> /dev/stderr
+            exit 1
+        }
+    fi
 
-(shopt -s nullglob
- for PROJECT in "$DIR"/*
- do
-     echo "Dumping package $PROJECT" >> /dev/stderr
-     "$BASE/dump-package" "$PROJECT"
- done)
-
-rm -rf "$DIR"
+    PROJECT=$(readlink -f "$DIR/$PKGDIR")
+    echo "Dumping package $PROJECT" >> /dev/stderr
+    "$BASE/dump-package" "$PROJECT"
+done
diff --git a/dump-package b/dump-package
--- a/dump-package
+++ b/dump-package
@@ -1,6 +1,10 @@
-#! /usr/bin/env nix-shell
-#! nix-shell -i bash -p bash jq
+#!/usr/bin/env bash
 set -e
+
+command -v jq > /dev/null || {
+    echo "dump-package requires jq, aborting" >> /dev/stderr
+    exit 1
+}
 
 BASE_=$(dirname "$0")
 BASE=$(readlink -f "$BASE_")
