Don't use stderr

diff --git a/getArities b/getArities
--- a/getArities
+++ b/getArities
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 command -v jq > /dev/null || {
-    echo "ERROR: getArities requires jq" >> /dev/stderr
+    echo "ERROR: getArities requires jq" 1>&2
     exit 1
 }
 
